type Query {
    tasks: [Task!]!
}

type Task {
    id: ID!
    title: String
    description: String
    createdBy: User!
    assignedTo: User
}

type User {
    id: ID!
    username: String
    name: String
}